[package]
name = "cases_notifier"
version = "0.2.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
winres = "0.1"

[dependencies]
chrono = "0.4.24"
eframe = "0.21.3"
egui = "0.21.0"
image = "0.24.2"